# Generated by Django 5.0.2 on 2024-03-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dukandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=50)),
                ('ShopID', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Dukan_Image', models.ImageField(upload_to='dukanimages/')),
            ],
        ),
    ]
