# Generated by Django 5.0.2 on 2024-03-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('Category', models.CharField(max_length=50)),
                ('BookPrice', models.IntegerField()),
                ('Image', models.ImageField(upload_to='bookimages/')),
            ],
        ),
    ]
