# Generated by Django 5.0.2 on 2024-03-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Uploader',
            field=models.CharField(default='Ramesh Dukanwala', max_length=50),
        ),
    ]
