# Generated by Django 5.0.2 on 2024-03-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_book_uploader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bookname', models.CharField(max_length=50)),
                ('question1', models.CharField(max_length=150)),
                ('answer1', models.CharField(max_length=500)),
                ('question2', models.CharField(max_length=150)),
                ('answer2', models.CharField(max_length=500)),
                ('question3', models.CharField(max_length=150)),
                ('answer3', models.CharField(max_length=500)),
                ('question4', models.CharField(max_length=150)),
                ('answer4', models.CharField(max_length=500)),
                ('question5', models.CharField(max_length=150)),
                ('answer5', models.CharField(max_length=500)),
                ('question6', models.CharField(max_length=150)),
                ('answer6', models.CharField(max_length=500)),
                ('question7', models.CharField(max_length=150)),
                ('answer7', models.CharField(max_length=500)),
                ('question8', models.CharField(max_length=150)),
                ('answer8', models.CharField(max_length=500)),
                ('question9', models.CharField(max_length=150)),
                ('question10', models.CharField(max_length=150)),
                ('answer10', models.CharField(max_length=500)),
            ],
        ),
    ]
