# Generated by Django 5.0.2 on 2024-03-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_question_answer9_alter_question_question1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer9',
            field=models.CharField(default='yes', max_length=500),
        ),
    ]
