# Generated by Django 5.0.2 on 2024-03-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_alter_question_answer9'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=50)),
                ('StudentID', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('User_Image', models.ImageField(upload_to='userimages/')),
            ],
        ),
    ]
