# Generated by Django 5.0.2 on 2024-03-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='PDF',
            field=models.FileField(default='mypdf.pdf', upload_to='bookpdfs/'),
        ),
    ]
