# Generated by Django 5.0.2 on 2024-03-17 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_borrower_points_borrower_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='BorrowDate',
            field=models.DateField(default=datetime.datetime(1981, 9, 15, 0, 0)),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='RegDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 17, 7, 46, 5, 958506)),
        ),
    ]
