# Generated by Django 5.0.2 on 2024-03-20 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_borrower_borrowdate_alter_borrower_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='BorrowedBook',
            field=models.CharField(default='Atomic Habits', max_length=50),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='RegDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 21, 18, 2, 850185)),
        ),
    ]
