# Generated by Django 5.0.2 on 2024-03-20 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_borrower_borrowedbook_alter_borrower_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='RegDate',
            field=models.DateField(default=datetime.datetime(2024, 3, 20, 21, 18, 26, 255510)),
        ),
    ]
